---
name: Fetch
on:
  workflow_call:
permissions: {}
concurrency:
  group: fetch-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
      with:
        aqua_version: v2.64.0
    - name: Restore go mod cache
      id: go-mod-cache-restore
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        key: go-mod-${{ hashFiles('**/go.sum') }}
        path: ~/go/pkg/mod/
    - name: Fetch go mod
      run: |-
        task app:mod
    - name: Save go mod cache
      if: github.ref == 'refs/heads/main' && steps.go-mod-cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        key: ${{ steps.go-mod-cache-restore.outputs.cache-primary-key }}
        path: ~/go/pkg/mod/
